---
title: "09-transducer"
author: "Marc Jones"
date: "October 31, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load the libraries
```{r, message = FALSE}
library(tidyverse)
library(knitr)
library(broom)
library(ggfortify)
library(here)
```





Basic plot of bite force against SVL. 

```{r, message = FALSE}
# All individuals
ggplot(pog, aes(x = SVL, y = BiteForce, 
                colour = Transd, fill = Transd, shape = Transd)) +
  geom_point(alpha = 0.8, na.rm = TRUE) +
  #geom_smooth(method = lm, se = TRUE, alpha = 0.2) +
  scale_colour_manual(values = c("orange1", "red", "cornflowerblue")) +
  scale_fill_manual(values = c("orange1", "red", "cornflowerblue")) +
  theme_bw(base_size = 14) +
  #theme(legend.title = element_blank()) +
  ylab("Bite Force (N)") +
  xlab("SVL (mm)")

#ggsave(here("figures/NotLOG_svl-bf.png"))
```

Plot to demonstrate age and transducer.

```{r, message = FALSE}
# All individuals
ggplot(pog, aes(x = SVL, y = BiteForce, 
                colour = Age, fill = Age, shape = Transd)) +
  geom_point(alpha = 0.8, na.rm = TRUE) +
  #geom_smooth(method = lm, se = TRUE, alpha = 0.2) +
  scale_colour_manual(values = c("orange1", "red", "cornflowerblue")) +
  scale_fill_manual(values = c("orange1", "red", "cornflowerblue")) +
  theme_bw(base_size = 14) +
  #theme(legend.title = element_blank()) +
  ylab("Bite Force (N)") +
  xlab("SVL (mm)")

#ggsave(here("figures/NotLOG_svl-bf.png"))
```


This creates a plot of log(BF) vs log(SVL) colour coded by trans

Figure S2

```{r, message = FALSE}
# All individuals
ggplot(pog, aes(x = log(SVL), y = log(BiteForce), 
                colour = Transd, fill = Transd, shape = Transd)) +
  geom_point(alpha = 0.8, na.rm = TRUE) +
  #geom_smooth(method = lm, se = TRUE, alpha = 0.2) +
  scale_colour_manual(values = c("orange1", "red", "cornflowerblue")) +
  scale_fill_manual(values = c("orange1", "red", "cornflowerblue")) +
  theme_bw(base_size = 14) +
  #theme(legend.title = element_blank()) +
  ylim(0, 5)+
  xlim(4, 5.5) +
  ylab("log(Bite Force) (N)") +
  xlab("log(SVL) (mm)")

#ggsave(here("figures/TransD-svl-bf.png"))
```


```{r, message = FALSE}
# All individuals
ggplot(pog, aes(x = log(SVL), y = log(BiteForce), 
                colour = Transd, fill = Transd, shape = Transd)) +
  geom_point(alpha = 0.8, na.rm = TRUE) +
  geom_smooth(method = lm, se = TRUE, alpha = 0.2) +
  scale_colour_manual(values = c("orange1", "red", "cornflowerblue")) +
  scale_fill_manual(values = c("orange1", "red", "cornflowerblue")) +
  theme_bw(base_size = 14) +
  #theme(legend.title = element_blank()) +
  ylim(0, 5)+
  xlim(4, 5.5) +
  ylab("log(Bite Force) (N)") +
  xlab("log(SVL) (mm)")

#ggsave(here("figures/TransD-svl-bf.png"))
```

This creates a plot of log(BF) vs log(Mass) colour coded by trans

```{r, message = FALSE}
# All individuals
ggplot(pog, aes(x = log(Mass), y = log(BiteForce), 
                colour = Transd, fill = Transd, shape = Transd)) +
  geom_point(alpha = 0.8, na.rm = TRUE) +
  #geom_smooth(method = lm, se = TRUE, alpha = 0.2) +
  scale_colour_manual(values = c("orange1", "red", "cornflowerblue")) +
  scale_fill_manual(values = c("orange1", "red", "cornflowerblue")) +
  theme_bw(base_size = 14) +
  #theme(legend.title = element_blank()) +
  ylim(0, 5)+
  xlim(1, 5.5) +
  ylab("log(Bite Force) (N)") +
  xlab("log(Mass) (g)")

#ggsave(here("figures/TransD-svl-bf.png"))
```

